exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tsconfig.json
  - webpack.config.json
  - LISCENCE
  - CNAME
  - .gitignore
title: Eric Damtoft
links:
  medium: https://medium.com/@edamtoft
  github: https://github.com/edamtoft
  twitter: https://twitter.com/ericdamtoft
  dealeron: https://medium.com/dealeron-dev
mediumposts:
  - url: https://medium.com/dealeron-dev/electron-and-xss-e9ecef1c7325
    title: "Electron and XSS: How Small Bugs Escalate to Big Problems"